A = input("digite algo: ")
print("o tipo primitovo desse valor é ?", type(A))
print("é um numero?", A.isnumeric())
print("tem espaco?", A.isspace())
print("tem letra?", A.isalpha())
print("tem letra e numero?", A.isalnum())
print("está em caps ?", A.isupper())
print("está sem caps ?", A.islower())
print("esta captalizada ?", A.istitle())